### ISSUE TITLE
Available storage stuck at 105MB

### ISSUE THREAD

**Issue by AndreiButoi** [noia-network/noia-node-gui#1]
Available storage is mesured wrong, i tryed on two diffrent PC with windows 10pro x64 and on both is 105MB.
It will be nice te setup in settings the amount of storage available for noia.

**Comment by Dancia** [comment]
The storage is not "stuck". It is set in parameters and is equal to value you wish NOIA to utilize for caching and is NOT equal to total disk space available by system. The storage space parameter is not exposed in GUI for now, but definitely will be in future releases.

**Comment by bitcoinpaidme** [comment]
I have the same issue after connecting to NOIA node, I can only see 105MB available storage, can I change this? Do I need to change this?  I have 4.7GB HDD free space. Please advise - Thank you

**Comment by Dancia** [comment]
@bitcoinpaidme technically, you could change it, but the parameter is not exposed in GUI. There is no much reason to change it at given time of writing, since we still aren't pushing content for users. Once we start pushing content, we will expose storage parameter to be changeable via GUI.

**Comment by bitcoinpaidme** [comment]
Thanks for the reply.

I started the interface yesterday morning at approx 2AM GMT BST it is now
19:37pm approx 17 hrs later and the time says it has been running for 03hrs
17mins 17 secs


Why is that?


Pls advise



Thank you

**Comment by Dancia** [comment]
@bitcoinpaidme by any chance you are running NOIA Node GUI v0.1.0? It is known that v0.1.0 displays time online to user invalidly. If so, please update to latest version found at https://github.com/noia-network/noia-node-gui/releases (at the time of writing it is v0.1.1).

Please note that it only affects the displayed time to user, the ACTUAL time is calculated in master so not a single second online is lost.

**Comment by AndreiButoi** [comment]
Dudring this time did the application stay connected? It happens to disconnect and does not auto-reconnect. Maybe that was the reason the connection time was not calculate

**Comment by bitcoinpaidme** [comment]
How long is the time you can see my node is running for? because when I minimise or turn of my screen it go’s to sleep and 12hrs should be 29hrs
