### ISSUE TITLE
Problem when install!

### ISSUE THREAD

**Issue by vijaymalaysia** [noia-network/noia-node-gui#10]
![error1](https://user-images.githubusercontent.com/40222228/41327133-ca9efe68-6ef4-11e8-8453-4f3cd6b1b0ce.JPG)

Encountered the following error while install
[SquirrelSetup.log](https://github.com/noia-network/noia-node-gui/files/2096412/SquirrelSetup.log)

**Comment by Joseerdriiguez** [comment]
Having the same problem!!

**Comment by Dancia** [comment]
Please try the latest Node GUI version available in [releases](https://github.com/noia-network/noia-node-gui/releases).

At the time of writing it is version 0.2.5.

**Comment by Dancia** [comment]
Duplicate of #9.
