### ISSUE TITLE
Connected but no records for download and upload speed

### ISSUE THREAD

**Issue by Iamdeadlyz** [noia-network/noia-node-gui#13]
![image](https://user-images.githubusercontent.com/29373963/41349845-bd5add86-6f43-11e8-9284-7e1d4e910ef2.png)

Is this normal?

**Comment by ouallada** [comment]
i have the same thing

**Comment by Iamdeadlyz** [comment]
![image](https://user-images.githubusercontent.com/29373963/41353639-6142e992-6f4f-11e8-831b-20cbfa79ac7d.png)

1 hours passed and still no data nor records. Waiting for devs reply ^-^

**Comment by Iamdeadlyz** [comment]
Oh well found the reason. Read here https://github.com/noia-network/noia-node-gui/issues/3#issuecomment-395571547

Duplicate of 3
