### ISSUE TITLE
Auto-reconnect is not working

### ISSUE THREAD

**Issue by Iamdeadlyz** [noia-network/noia-node-gui#14]
Tried testing the auto-reconnect feature

I unplugged the ethernet cable -> failed connectiong will reconnect after 60 seconds popped out
Plugged it back -> waiting for 60 seconds and still not reconnected

What worries me is that it does not show "reconnecting" but only connect. So I have to go and click connect again and the auto-reconnect is not working.

**Comment by Dancia** [comment]
What OS are you running GUI on?

**Comment by mjm29se** [comment]
Same situation for me. W7 pro 64-bit. Does not appear to auto reconnect

**Comment by Iamdeadlyz** [comment]
@Dancia  running on Win 10

![image](https://user-images.githubusercontent.com/29373963/41383278-839b2cc2-6fa2-11e8-866a-9bb17e7f9170.png)

**Comment by Dancia** [comment]
We are currently working on improving auto reconnection feature: #17, #18, #19 to help us better understand the problem.

**Comment by sabelosimelane** [comment]
Also same problem on Win 10. Left it running for 2 days, and on both days lost connection after about one and half hour and does not reconnect automatically.

**Comment by Dancia** [comment]
Hi.

@Iamdeadlyz  @mjm29se @sabelosimelane. Please try latest NOIA Node GUI version. Att the moment of writing it is 0.3.12 and try manually plugging out ethernet cabel or powering off router, to reproduce error.

Let me know about results!

Note: If you already have 0.3.12 and it was downloaded before 06:43:21, Saturday, 16 June 2018 GMT, please re-download it.

**Comment by sabelosimelane** [comment]
Worked for me! Reconnected successfully without my intervention once I plugged the ethernet cable back in.

**Comment by Iamdeadlyz** [comment]
Cool! It worked! Thank you ^-^ , Cheers~

**Comment by mjm29se** [comment]
Hi,
Issue is not fixed for me.

On 16 June 2018 at 11:44, Ian Emmanuel M. Enanoria <notifications@github.com

**Comment by Dancia** [comment]
@mjm29se can you give more details please? What error messages are you seeing, etc...

**Comment by mjm29se** [comment]
Hi, see attached files

**Comment by Iamdeadlyz** [comment]
@mjm29se  try attaching the files again, I can't see anything

**Comment by mjm29se** [comment]
I attached via e-mail. But here they are. 

![2018-06-18_07-20-04](https://user-images.githubusercontent.com/40214099/41550552-68e86932-7329-11e8-9de0-5409073f9d44.png)

![2018-06-18_07-20-22](https://user-images.githubusercontent.com/40214099/41550556-6d383da0-7329-11e8-9795-808a2f01eca8.png)

**Comment by Dancia** [comment]
Are you 100 % sure that you are using v0.3.12 Node GUI version?

**Comment by mjm29se** [comment]
yes, 
![2018-06-19_08-13-22](https://user-images.githubusercontent.com/40214099/41579817-cb08264c-7398-11e8-9700-7f50d95e8275.png)

**Comment by mjm29se** [comment]
I restarted my computer, and was prompted to install a java update, after that and a few tries it connected automatically, there was an error message that wallet is already connected to master-node but the next re-connection worked fine. :) side note, what stops someone else from using my wallet address on their own Node GUI? Not that it makes any sense for someone to do so but just asking.

![2018-06-19_09-02-18](https://user-images.githubusercontent.com/40214099/41582312-9b27ffde-73a1-11e8-88b2-e9f63d0998e8.png)

**Comment by Dancia** [comment]
1. We do not use Java.
2. Are you are of message in comment above:
https://github.com/noia-network/noia-node-gui/issues/14#issuecomment-397793204
> **Note: If you already have 0.3.12 and it was downloaded before 06:43:21, Saturday, 16 June 2018 GMT, please re-download it.**

**Comment by mjm29se** [comment]
1. Co-incidence then.
2. Yes, as you can see from my downloads folder, I installed 0.3.12 on 16th June @07:35 GMT  and again
on 18th June @08:27 GMT

![2018-06-19_08-13-22](https://user-images.githubusercontent.com/40214099/41590700-ed3b61ec-73b7-11e8-8f6f-7b9bd27e1ec6.png)

In any case the issue was resolved somehow.

**Comment by sabelosimelane** [comment]
Today I left the GUI connected but when I returned it was disconnected, for some reason the re connection did not work. I just downloaded and installed the latest version.

I will report if the issue persists.

**Comment by Iamdeadlyz** [comment]
Closing this issue now.. @sabelosimelane  if issue persists kindly make another issue thank you.
