### ISSUE TITLE
Connected but no traffic

### ISSUE THREAD

**Issue by GreggySera** [noia-network/noia-node-gui#16]
Dear people at NOIA,
I have successfully installed the NOIA Client for Mac OS [latest version at the time of this message], cleared port 7676, added my ETH wallet address and connected to the network. However, I see no traffic, no connections, no cached data, no bandwidth being used and seems that is doing virtually nothing. Is this normal? Note I have been connected for _just_ a couple of hours or so.
I've got a fibre to the premise 100Mbps symmetric connection with unlimited data, so bandwidth should not be a limiting factor.
Also, the available storage is limited to 105 MB and the little callout message when hovering over the question mark button reads **Available storage is the amount of storage in your device which is allowed to be used by NOIA network. You will soon be able to change**; will I need to download another version of the software when more storage allocation is allowed? Or will it be pushed to the current version?
Do you have any clue about this? 
Please let me know as soon as you have the chance, and looking forward to seeing more developments.

**Comment by Dancia** [comment]
>  However, I see no traffic, no connections, no cached data, no bandwidth being used and seems that is doing virtually nothing.

Refer to #3.

>will I need to download another version of the software when more storage allocation is allowed? Or will it be pushed to the current version?

Currently new versions have to be manually downloaded, but we are working on auto updater feature #20.

**Comment by GreggySera** [comment]
Thanks Dancia, and sorry about the repeated question - I missed the Closed posts.
Also, this morning I found that the time counter stopped where I left it last night, so it seems to Stop when the computer screen goes off - but the machine is still awake, not going into sleep, I am sure about that because other model simulations have been running through the night OK. Can this be a bug/issue?
Also, I understand there is a reward for leaving the node running of 200 NOIA tokens every week. I was wondering, where will these be accredited? The wallet address I inserted is for the Ethereum currency. Is there a ETH equivalent for each NOIA token. Sorry in advance if the question comes across as redundant but I am a novice in the cryptocurrency landscape.
Feeling confident you understand.
Please let me know.

**Comment by Dancia** [comment]
NOIA will be an Ethereum ERC20 compatible token. Every valid ETH address can receive and hold ERC20 tokens. You will be able to see and use them depending on the ETH wallet provider you use. As long as you can control (have private keys and can transfer from one wallet provider to another) your ETH address you can see/receive/send ERC20 tokens. If you use some cold wallet like Trezor/Ledger etc. make sure your cold wallet is ERC20 compatible or that you can export your wallet private keys.
