### ISSUE TITLE
JavaScript error

### ISSUE THREAD

**Issue by mjm29se** [noia-network/noia-node-gui#21]
Happened when my router lost power and reset itself.

![2018-06-15_00-54-45](https://user-images.githubusercontent.com/40214099/41442514-e962c912-7037-11e8-991f-1331b5a9b296.png)

![2018-06-15_00-55-22](https://user-images.githubusercontent.com/40214099/41442522-f3ea80aa-7037-11e8-9d57-2f410dcbd065.png)

**Comment by Dancia** [comment]
Please try latest NOIA Node GUI version. Att the moment of writing it is 0.3.12 and try manually plugging out ethernet cabel or powering off router, to reproduce error.

**Note**: If you already have 0.3.12 and it was downloaded before _06:43:21, Saturday, 16 June 2018 GMT_, please re-download it.
