### ISSUE TITLE
Minimize to tray

### ISSUE THREAD

**Issue by Dancia** [noia-network/noia-node-gui#26]
Open to discussion if minimizing to tray feature should be implemented or not.

**Comment by sabelosimelane** [comment]
Makes sense to implement. Most people will have GUI running 24/7. To reduce taskbar clutter, I personally would prefer it sitting in the system tray.

**Comment by mjm29se** [comment]
upvote from me

**Comment by MartynasZilinskas** [comment]
This feature is live with the newest update on Windows release: [v0.3.13](https://github.com/noia-network/noia-node-gui/releases/tag/v0.3.13)
