### ISSUE TITLE
Running same wallet from different computers

### ISSUE THREAD

**Issue by Zippo85** [noia-network/noia-node-gui#35]
I was wondering whether you can install NOIA on multiple machines using the same wallet?
As previously when I try to open NOIA on a different machine and use the same wallet I get a message saying "An instance of this wallet is already in use" or something along those lines. At this point I'm not sure if this disrupts my NOIA sync or not?

I'd like to use the same wallet with different accounts and have the total uptime to the server for both count towards earning tokens.

**Comment by MartynasZilinskas** [comment]
One KYC is eligible for one running node rewards. If you have any other questions, you can ask them in our Telegram channel https://t.me/NoiaNetwork/.
