### ISSUE TITLE
Can't add Wallet

### ISSUE THREAD

**Issue by ghost** [noia-network/noia-node-gui#36]
Apologies - i was having trouble adding wallet because i didn't know where to click. It is not immediately obvious because there is a blank space next to wallet that doesn't look "clickable". 

Suggest changing the wallet entry box to a different colour.

**Comment by MartynasZilinskas** [comment]
Added in [v0.4.0](https://github.com/noia-network/noia-node-gui/releases/tag/v0.4.0).
