### ISSUE TITLE
V.0.3.13: Time Counter Stops when screen goes off & Suspicious Upload Volume

### ISSUE THREAD

**Issue by GreggySera** [noia-network/noia-node-gui#37]
Dear people at NOIA,
I would like to report that V.0.3.13 on Mac shows some odd behaviors:
1. The connection time counter stops ticking/counting when the screen goes off - note this was an issue in the previous version also; and 
2. The upload volume does not make sense: the screenshot attached inline below shows an uploaded volume of 1TB, which does not match the volume for uploaded data in both my ISP account and router - it should be much less than that. 
Please fix, and hope this helps.

<img width="729" alt="screen shot 2018-07-12 at 07 02 05" src="https://user-images.githubusercontent.com/40267510/42603870-4719c8b0-85a2-11e8-889b-7d5be999bdc2.png">

**Comment by MartynasZilinskas** [comment]
Thanks for contributing to this issue. I am closing this issue to clear clutter. If this issue persists, please re-open the issue.
