### ISSUE TITLE
Windows release version (.exe) does not pass immediate Avast scan

### ISSUE THREAD

**Issue by kolibrizas** [noia-network/noia-node-gui#38]
**Describe the bug**
Trying to install **noia-node-gui-0.4.0-win.exe** caused Avast antivirus to send the file to their server for additional scanning.

**To Reproduce**
1. Go to [https://github.com/noia-network/noia-node-gui/releases](https://github.com/noia-network/noia-node-gui/releases)
2. Click on **noia-node-gui-0.4.0-win.exe**
3. Launch the downloaded file
4. Optional information. Not the main issue though. Windows doesn't trust the file, you need to go to More Information and click Proceed, but I didn't make a screenshot unfortunately
5. Avast Internet Security interrupts execution by sending the file to their internal scanning repository

**Expected behavior**
Installs without additional security checks by Avast antivirus

**Screenshots**

![2018-07-18_00h59_32](https://user-images.githubusercontent.com/3621260/42897259-15a1886a-8ac8-11e8-812b-055aa7846314.png)
![2018-07-18_20h14_49](https://user-images.githubusercontent.com/3621260/42897262-1875deba-8ac8-11e8-9015-eca1c395fbca.png)

**Info:**
 - OS: Windows 10 Pro
 - Version: 1803

**Comment by MartynasZilinskas** [comment]
We cannot control anti-virus behavior. This might have been a random check. Either way, we are working on code signing certificates.

Text snippet from release notes:
>Ignore and accept warnings of app being from unknown publisher. The application is open source and we are acquiring Code Signing Certificates.
