### ISSUE TITLE
Available storage: wrong conversion displayed

### ISSUE THREAD

**Issue by AndreiButoi** [noia-network/noia-node-gui#4]
With the Windows application, the available storage space is mislabeled due to conversion from bytes to Gica bytes.
Ex: in settings.json -> "storage.size": "53687091200" in correct conversion this mean 50GB, but the app display 54TB.

**Comment by Dancia** [comment]
@AndreiButoi please note, that once the bug will be fixed, the calculations will be displayed in TB, GB, MB, kB and B's, not TiB, GiB, MiB, kiB's. For more informatiom refer to [MiB vs MB- Whats the Difference?](https://blog.digilentinc.com/mib-vs-mb-whats-the-difference/) or [Orders of magnitude](https://en.wikipedia.org/wiki/Orders_of_magnitude_(data)) or similar source.
