### ISSUE TITLE
Connections at 0 yet app is downloading data

### ISSUE THREAD

**Issue by MeijeSibbel** [noia-network/noia-node-gui#46]
**Describe the bug**

**To Reproduce**

Start the app, wait for it to start downloading.

**Expected behavior**

Connections is higher than 0 if downloading data = true.

**Screenshots**

**Info:**
 - OS: windows 10 home.
 - Version 0.0.5

**Additional context**

**Comment by MartynasZilinskas** [comment]
I am closing this issue, because there was a lot of changes recently. If issue occurs again, please open new issue. Thank you.
