### ISSUE TITLE
[Linux AppImage] Auto reconnect

### ISSUE THREAD

**Issue by vmag** [noia-network/noia-node-gui#51]
**Environment**:  Fedora 28, Node GUI v.0.6.0, AppImage
**Steps to reproduce**: Select "Auto reconnect" checkbox, restart app.
**Expected Result:** Node GUI must reconnect to master after app restart or start.
**Actual Result**: Need to press Connect, to connect to master.

**Comment by MartynasZilinskas** [comment]
Fixed in the [v0.7.0](https://github.com/noia-network/noia-node-gui/releases/tag/v0.7.0) release.
