### ISSUE TITLE
[Linux Appimage]  Storage space

### ISSUE THREAD

**Issue by vmag** [noia-network/noia-node-gui#52]
**Environment:** Fedora 28, Node GUI v.0.6.0, AppImage
**Steps to reproduce:** Storage size, input any number > 12335 MB or < 100 MB
**Expected Result:** Node GUI must show message "Not valid storage space"
**Actual Result:** Can input any number from 1MB to google 
([noia-node] Setting configuration key=storage.size oldValue=1.048576e+86 newValue=1.048576e+24)

**Comment by MartynasZilinskas** [comment]
Fixed in the [v0.7.0](https://github.com/noia-network/noia-node-gui/releases/tag/v0.7.0) release.
