### ISSUE TITLE
[Linux Appimage] GUI Doesn`t init

### ISSUE THREAD

**Issue by jmarunix** [noia-network/noia-node-gui#54]
**Describe the bug**
The GUI of the app doesn't init and throws an error in the console.

**To Reproduce**
1. In the console ./noia-node-gui-0.6.1-linux-x86_64.AppImage
2. See error:

error: [noia-contents-client] uncaughtException: Cannot find module 'bignumber.js' date=Fri Sep 07 2018 21:49:11 GMT+0200 (CEST), pid=27899, uid=1000, gid=1000, cwd=/home/jmar/Escritorio/NOIA_NODE_GUI, execPath=/tmp/.mount_noia-nObezpy/noia-node-gui, version=v8.9.3, argv=[/tmp/.mount_noia-nObezpy/noia-node-gui], rss=116658176, heapTotal=39231488, heapUsed=20704584, external=349152, loadavg=[0.78271484375, 0.93310546875, 1.31005859375], uptime=501151, trace=[column=15, file=module.js, function=Module._resolveFilename, line=543, method=_resolveFilename, native=false, column=12, file=/tmp/.mount_noia-nObezpy/resources/electron.asar/common/reset-search-paths.js, function=Module._resolveFilename, line=35, method=_resolveFilename, native=false, column=25, file=module.js, function=Module._load, line=473, method=_load, native=false, column=17, file=module.js, function=Module.require, line=586, method=require, native=false, column=18, file=internal/module.js, function=require, line=11, method=null, native=false, column=17, file=/tmp/.mount_noia-nObezpy/resources/app.asar/node_modules/truffle-contract/node_modules/web3/lib/utils/utils.js, function=null, line=37, method=null, native=false, column=3, file=/tmp/.mount_noia-nObezpy/resources/app.asar/node_modules/truffle-contract/node_modules/web3/lib/utils/utils.js, function=null, line=643, method=null, native=false, column=30, file=module.js, function=Module._compile, line=642, method=_compile, native=false, column=10, file=module.js, function=Module._extensions..js, line=653, method=.js, native=false, column=32, file=module.js, function=Module.load, line=561, method=load, native=false], stack=[Error: Cannot find module 'bignumber.js',     at Module._resolveFilename (module.js:543:15),     at Function.Module._resolveFilename (/tmp/.mount_noia-nObezpy/resources/electron.asar/common/reset-search-paths.js:35:12),     at Function.Module._load (module.js:473:25),     at Module.require (module.js:586:17),     at require (internal/module.js:11:18),     at Object.<anonymous> (/tmp/.mount_noia-nObezpy/resources/app.asar/node_modules/truffle-contract/node_modules/web3/lib/utils/utils.js:37:17),     at Object.<anonymous> (/tmp/.mount_noia-nObezpy/resources/app.asar/node_modules/truffle-contract/node_modules/web3/lib/utils/utils.js:643:3),     at Module._compile (module.js:642:30),     at Object.Module._extensions..js (module.js:653:10),     at Module.load (module.js:561:32)]

**Expected behavior**

**Screenshots**

**Info:**
 - OS: Fedora Linux 4.17.19-200.fc28.x86_64 #1 SMP Fri Aug 24 15:47:41 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
 - Version 8.11.4

**Additional context**

**Comment by MartynasZilinskas** [comment]
Thanks, it's already fixed with [v0.6.2](https://github.com/noia-network/noia-node-gui/releases/tag/v0.6.2).
