### ISSUE TITLE
GUI bug. 

### ISSUE THREAD

**Issue by Kingdeathmatch** [noia-network/noia-node-gui#58]
The GUI bug happens when you relocate the application from one monitor to the other as demonstrated in the attached file. 
When you relocate the app to the second monitor it bugs out and the cursor does not move with the app. The app becomes detached from where you have selected it. 
The cursor is still fluidly moving in a downward/right direction but only grabs app more effectivly in a upward left direction. 

I do have scaling on this gpu and use it as my second monitor is a 4k Samsung Series 6 TV. 
Gpu can handle it fine (1080ti OC). 

[2018-09-18 10-29-28.zip](https://github.com/noia-network/noia-node-gui/files/2390704/2018-09-18.10-29-28.zip)

**Comment by MartynasZilinskas** [comment]
I don't think this behavior that we can control. It could be an OS or electron specific issue that we have no control over.

Try creating the issue at electron's repository: https://github.com/electron/electron/issues.
