### ISSUE TITLE
Large amount of network traffic even when disconnected

### ISSUE THREAD

**Issue by PiranhaUK** [noia-network/noia-node-gui#65]
After updating to version 1.0.0 I've noticed a large increase in the amount of network traffic.

Bursts of ~150 MB D/L and ~60 MB U/L every 5 minutes periodically even after clicking "Connect" to disconnect the client. Network traffic only stops when closing down the application.

This is generating roughly 96 GB of network traffic every 24 hours. Is this expected? I was getting intermittent traffic previously but nothing on this scale and not so frequently.

1. Open Noia and Connect
2. Open Task Manager and monitor network traffic
3. Click "Connect" to disconnect noia
4. Open Task Manager and same network traffic is still bursting every 5 mins.

-   OS: Windows 10
-   Version 1.0.0

![image](https://user-images.githubusercontent.com/38222919/48730894-94e01200-ec33-11e8-8b5a-5f3bc667594c.png)

![image](https://user-images.githubusercontent.com/38222919/48730865-7c6ff780-ec33-11e8-9a6d-3a96c3031611.png)

**Comment by Dancia** [comment]
We'll try to address this issue in a hotfix we are planning to release in next 24 hours.

**Comment by NojusLi** [comment]
Hi guys, v.1.0.1 should solve this issue.
Download link: https://github.com/noia-network/noia-node-gui/releases/tag/v1.0.1

**Comment by PiranhaUK** [comment]
Brilliant. That's dropped to ~90MB per hour now which is MUCH better..... ;o)
