### ISSUE TITLE
Failed to start/install (Windows 32-bit)

### ISSUE THREAD

**Issue by Ksotillo** [noia-network/noia-node-gui#9]
Hello Sir, I'm having this issue when trying to install the application:

![error](https://user-images.githubusercontent.com/36375180/41321583-91414770-6e72-11e8-8e28-4e71d1004320.png)

[SquirrelSetup.log](https://github.com/noia-network/noia-node-gui/files/2096067/SquirrelSetup.log)

**Comment by Dancia** [comment]
Please try the latest Node GUI version available in [releases](https://github.com/noia-network/noia-node-gui/releases).

At the time of writing it is version 0.2.5.
